# Generated by Django 5.2.14 on 2026-05-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("bpm", models.FloatField(blank=True, null=True)),
                (
                    "key_detected",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_minor", models.BooleanField(default=False)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("waveform_data", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
